version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sidangakhir-backend
    volumes:
      - ./backend:/var/www
    depends_on:
      - db
    networks:
      - app-network
    entrypoint: ["/var/www/start.sh"]

  backend-nginx:
    image: nginx:alpine
    container_name: sidangakhir-backend-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/conf.d/backend.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sidangakhir-frontend
    volumes:
      - ./frontend:/var/www
    networks:
      - app-network

  frontend-nginx:
    image: nginx:alpine
    container_name: sidangakhir-frontend-nginx
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - ./frontend:/var/www
      - ./docker/nginx/conf.d/frontend.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: sidangakhir-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: sistem_sidangakhir
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # <- password root kosong
    ports:
      - "3307:3306"  # port host:container
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sidangakhir-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8081:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
